name: json-templater
description: Renders JSON from a base file, injecting field/value pairs into the body

inputs:
  json-file-path:
    description: Path to JSON file to use as base for rendering
    required: true
  output-file-name:
    description: File name for outputting rendered json
    default: rendered.json
  field-value-pairs:
    description: |
      Multiline path/value pairs for injecting values into the supplied JSON file according to the JSON paths specified.
      Each path/value entry should be separated by a newline, and a colon is used as the separator between a path and
      its corresponding value.
    required: true

outputs:
  rendered-json-file:
    description: JSON file rendered from provided inputs

runs:
  using: docker
  image: docker://ghcr.io/georgepstaylor/render-json-template:v0.0.7
  args:
    - ${{ inputs.json-file-path }}
    - ${{ inputs.field-value-pairs }}
    - ${{ inputs.output-file-name }}
